# ==============================
# Server
# ==============================
server.port=8080

# ==============================
# PostgreSQL DataSource
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/noteshub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# Jackson
# ==============================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.default-property-inclusion=non_null

# ==============================
# JWT
# ==============================
# A dummy 256-bit secret for local dev: 7b844caec1c8b3e8e19b5b5c900e5720d20ddec2c40c11438902d3ee06cfb0a8
jwt.secret=7b844caec1c8b3e8e19b5b5c900e5720d20ddec2c40c11438902d3ee06cfb0a8
# 1 day expiration
jwt.expiration=86400000
